#include "WriteEnableForThreadsAt_ServerOutputSend__Framework.h"
#include "../include/WriteEnableForThreadsAt_ServerOutputSend__App.h"
#include "../include/WriteEnableForThreadsAt_ServerOutputSend__Control.h"
#include "../include/WriteEnableForThreadsAt_ServerOutputSend__Global.h"
#include <iostream>
CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend__App* CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend__Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend__App;
CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend__Global* CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend__Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_ServerOutputSend__Global;
// public.
CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend__Framework::WriteEnableForThreadsAt_ServerOutputSend__Framework()
{
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerOutputSend__Framework();
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerOutputSend__Framework();
}
CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend__Framework::~WriteEnableForThreadsAt_ServerOutputSend__Framework()
{
	delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend__App;
	delete _stat_CLASS_ptr_WriteEnableForThreadsAt_ServerOutputSend__Global;
}
CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend__App* CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend__App() {
	return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend__App();
}
CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend__Global* CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend__Global() {
	return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend__Global();
}
void CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend__Framework::dyn_REG_boot1_DEFINE_WriteEnableForThreadsAt_ServerOutputSend__Framework(WriteEnableForThreadsAt_ServerOutputSend__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend__App__Control()->dyn_REG_boot1_DEFINE_WriteEnableForThreadsAt_ServerOutputSend__Control(obj);
}
void CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend__Framework::dyn_REG_boot2_SUBSTANTIATE_WriteEnableForThreadsAt_ServerOutputSend__Framework(WriteEnableForThreadsAt_ServerOutputSend__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend__App__Control()->dyn_REG_boot2_SUBSTANTIATE_WriteEnableForThreadsAt_ServerOutputSend__Control(obj);
}
void CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend__Framework::dyn_REG_boot3_INITIALISE_WriteEnableForThreadsAt_ServerOutputSend__Framework(WriteEnableForThreadsAt_ServerOutputSend__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend__App__Control()->dyn_REG_boot3_INITIALISE_WriteEnableForThreadsAt_ServerOutputSend__Control(obj);
}
void CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend__Framework::dyn_boot4_PGM_INSTANTIATION_WriteEnableForThreadsAt_ServerOutputSend__Framework(WriteEnableForThreadsAt_ServerOutputSend__Framework* obj) {

}
void CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerOutputSend__Framework() {
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerOutputSend__App();
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerOutputSend__Global();
}
void CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerOutputSend__Framework() {
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerOutputSend__App();
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerOutputSend__Global();
}
// private.
void CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerOutputSend__App()
{
	_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend__App = nullptr;
}
void CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerOutputSend__Global()
{
	_stat_CLASS_ptr_WriteEnableForThreadsAt_ServerOutputSend__Global = NULL;
}
void CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerOutputSend__App()
{
	_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend__App = new class CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend__App();
	while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend__App() == nullptr) {}
}
void CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerOutputSend__Global()
{
	_stat_CLASS_ptr_WriteEnableForThreadsAt_ServerOutputSend__Global = new class CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend__Global();
	while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend__Global() == NULL) {}
}
CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend__App* CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend__App()
{
	return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend__App;
}
CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend__Global* CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend__Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_ServerOutputSend__Global;
	}