#include "../include/WriteEnableForThreadsAt_ServerOutputSend_Framework.h"
CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend_App* CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend_Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend_Framework_App;
	CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend_Global* CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend_Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_ServerOutputSend_Framework_Global;
// public.
	CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend_Framework::WriteEnableForThreadsAt_ServerOutputSend_Framework() {

	}
	CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend_Framework::~WriteEnableForThreadsAt_ServerOutputSend_Framework() {
		delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend_Framework_App;
		delete _stat_CLASS_ptr_WriteEnableForThreadsAt_ServerOutputSend_Framework_Global;
	}
	void CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend_Framework::dyn_CLASS_create_WriteEnableForThreadsAt_ServerOutputSend_Architecture() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerOutputSend_Framework();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerOutputSend_Framework();
	}
	void CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend_Framework::dyn_CLASS_create_WriteEnableForThreadsAt_ServerOutputSend_Global_and_Settings()
	{
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerOutputSend_Global();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerOutputSend_Global();
	}
	CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend_App* CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend_Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend_App() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend_App();
	}
	CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend_Global* CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend_Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend_Global() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend_Global();
	}
	void CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend_Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerOutputSend_Framework() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerOutputSend_App();
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerOutputSend_Global();
	}
	void CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend_Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerOutputSend_Framework() {
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerOutputSend_App();
	}
	void CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend_Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerOutputSend_Global() {
		pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerOutputSend_Global();
	}
// private.
	void CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend_Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerOutputSend_App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend_Framework_App = nullptr;
	}
	void CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend_Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerOutputSend_Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_ServerOutputSend_Framework_Global = nullptr;
	}
	void CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend_Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerOutputSend_App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend_Framework_App = new class CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend_App();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend_App() == nullptr) {}
	}
	void CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend_Framework::pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerOutputSend_Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_ServerOutputSend_Framework_Global = new class CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend_Global();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend_Global() == nullptr) {}
	}
	CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend_App* CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend_Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend_App()
	{
		return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend_Framework_App;
	}
	CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend_Global* CLIBWriteQueAtServerOutputSend::WriteEnableForThreadsAt_ServerOutputSend_Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerOutputSend_Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_ServerOutputSend_Framework_Global;
	}