#include <iostream>
#include "../include/LaunchEnableForConcurrentThreadsAt_Server__App.h"
#include "../include/LaunchEnableForConcurrentThreadsAt_Server__Framework.h"
#include "../include/LaunchEnableForConcurrentThreadsAt_Server__Control.h"
#include "../include/LaunchEnableForConcurrentThreadsAt_Server__Global.h"
CLIBLaunchQueAtServer::LaunchEnableForConcurrentThreadsAt_Server__App* CLIBLaunchQueAtServer::LaunchEnableForConcurrentThreadsAt_Server__Framework::_stat_CLASS_get_ptr_LaunchEnableForConcurrentThreadsAt_Server__App;
CLIBLaunchQueAtServer::LaunchEnableForConcurrentThreadsAt_Server__Global* CLIBLaunchQueAtServer::LaunchEnableForConcurrentThreadsAt_Server__Framework::_stat_CLASS_ptr_LaunchEnableForConcurrentThreadsAt_Server__Global;
// public.
CLIBLaunchQueAtServer::LaunchEnableForConcurrentThreadsAt_Server__Framework::LaunchEnableForConcurrentThreadsAt_Server__Framework()
{
	stat_CLASS_boot1_DEFINE_LaunchEnableForConcurrentThreadsAt_Server__Framework();
	stat_CLASS_boot3_INITIALISE_LaunchEnableForConcurrentThreadsAt_Server__Framework();
}
CLIBLaunchQueAtServer::LaunchEnableForConcurrentThreadsAt_Server__Framework::~LaunchEnableForConcurrentThreadsAt_Server__Framework()
{
	delete _stat_CLASS_get_ptr_LaunchEnableForConcurrentThreadsAt_Server__App;
	delete _stat_CLASS_ptr_LaunchEnableForConcurrentThreadsAt_Server__Global;
}

CLIBLaunchQueAtServer::LaunchEnableForConcurrentThreadsAt_Server__App* CLIBLaunchQueAtServer::LaunchEnableForConcurrentThreadsAt_Server__Framework::dyn_CLASS_get_ptr_LaunchEnableForConcurrentThreadsAt_Server__App() {
	return stat_CLASS_get_ptr_LaunchEnableForConcurrentThreadsAt_Server__App();
}
CLIBLaunchQueAtServer::LaunchEnableForConcurrentThreadsAt_Server__Global* CLIBLaunchQueAtServer::LaunchEnableForConcurrentThreadsAt_Server__Framework::dyn_CLASS_get_ptr_LaunchEnableForConcurrentThreadsAt_Server__Global() {
	return stat_CLASS_get_ptr_LaunchEnableForConcurrentThreadsAt_Server__Global();
}
void CLIBLaunchQueAtServer::LaunchEnableForConcurrentThreadsAt_Server__Framework::dyn_dyn_REG_boot1_DEFINE_LaunchEnableForConcurrentThreadsAt_Server__Framework(LaunchEnableForConcurrentThreadsAt_Server__Framework* obj) {
	std::cout << "entered dyn_REG_boot1_DEFINE_LaunchEnableForConcurrentThreadsAt_Server__Framework()." << std::endl;
	obj->dyn_CLASS_get_ptr_LaunchEnableForConcurrentThreadsAt_Server__Global()->dyn_REG_boot1_DEFINE_LaunchEnableForConcurrentThreadsAt_Server_Global();
	obj->dyn_CLASS_get_ptr_LaunchEnableForConcurrentThreadsAt_Server__App()->dyn_CLASS_get_ptr_LaunchEnableForConcurrentThreadsAt_Server__Control()->dyn_REG_boot1_DEFINE_LaunchEnableForConcurrentThreadsAt_Server__Control();
	std::cout << "exiting dyn_REG_boot1_DEFINE_LaunchEnableForConcurrentThreadsAt_Server__Framework()." << std::endl;
}
void CLIBLaunchQueAtServer::LaunchEnableForConcurrentThreadsAt_Server__Framework::dyn_REG_boot2_SUBSTANTIATE_LaunchEnableForConcurrentThreadsAt_Server__Framework(LaunchEnableForConcurrentThreadsAt_Server__Framework* obj) {
	std::cout << "entered dyn_REG_boot2_SUBSTANTIATE_LaunchEnableForConcurrentThreadsAt_Server__Framework()." << std::endl;
	obj->dyn_CLASS_get_ptr_LaunchEnableForConcurrentThreadsAt_Server__Global()->dyn_REG_boot2_SUBSTANTIATE_LaunchEnableForConcurrentThreadsAt_Server_Global();
	obj->dyn_CLASS_get_ptr_LaunchEnableForConcurrentThreadsAt_Server__App()->dyn_CLASS_get_ptr_LaunchEnableForConcurrentThreadsAt_Server__Control()->dyn_REG_boot2_SUBSTANTIATE_LaunchEnableForConcurrentThreadsAt_Server__Control();
	std::cout << "exiting dyn_REG_boot2_SUBSTANTIATE_LaunchEnableForConcurrentThreadsAt_Server__Framework()." << std::endl;
}
void CLIBLaunchQueAtServer::LaunchEnableForConcurrentThreadsAt_Server__Framework::dyn_REG_boot3_INITIALISE_LaunchEnableForConcurrentThreadsAt_Server__Framework(LaunchEnableForConcurrentThreadsAt_Server__Framework* obj) {
	std::cout << "entered dyn_REG_boot3_INITIALISE_LaunchEnableForConcurrentThreadsAt_Server__Framework()." << std::endl;
	obj->dyn_CLASS_get_ptr_LaunchEnableForConcurrentThreadsAt_Server__Global()->dyn_REG_boot3_INITIALISE_LaunchEnableForConcurrentThreadsAt_Server_Global();
	obj->dyn_CLASS_get_ptr_LaunchEnableForConcurrentThreadsAt_Server__App()->dyn_CLASS_get_ptr_LaunchEnableForConcurrentThreadsAt_Server__Control()->dyn_REG_boot3_INITIALISE_LaunchEnableForConcurrentThreadsAt_Server__Control();
	std::cout << "exiting dyn_REG_boot3_INITIALISE_LaunchEnableForConcurrentThreadsAt_Server__Framework()." << std::endl;
}
void CLIBLaunchQueAtServer::LaunchEnableForConcurrentThreadsAt_Server__Framework::dyn_dyn_PGM_boot4_INSTANTIATION_LaunchEnableForConcurrentThreadsAt_Server__Framework(LaunchEnableForConcurrentThreadsAt_Server__Framework* obj) {

}
// private.
void CLIBLaunchQueAtServer::LaunchEnableForConcurrentThreadsAt_Server__Framework::stat_CLASS_boot1_DEFINE_LaunchEnableForConcurrentThreadsAt_Server__App() {
	_stat_CLASS_get_ptr_LaunchEnableForConcurrentThreadsAt_Server__App = NULL;
}
void CLIBLaunchQueAtServer::LaunchEnableForConcurrentThreadsAt_Server__Framework::stat_CLASS_boot1_DEFINE_LaunchEnableForConcurrentThreadsAt_Server__Framework() {
	stat_CLASS_boot1_DEFINE_LaunchEnableForConcurrentThreadsAt_Server__App();
	stat_CLASS_boot1_DEFINE_LaunchEnableForConcurrentThreadsAt_Server__Global();
}
void CLIBLaunchQueAtServer::LaunchEnableForConcurrentThreadsAt_Server__Framework::stat_CLASS_boot1_DEFINE_LaunchEnableForConcurrentThreadsAt_Server__Global() {
	_stat_CLASS_ptr_LaunchEnableForConcurrentThreadsAt_Server__Global = NULL;
}
void CLIBLaunchQueAtServer::LaunchEnableForConcurrentThreadsAt_Server__Framework::stat_CLASS_boot3_INITIALISE_LaunchEnableForConcurrentThreadsAt_Server__App() {
	_stat_CLASS_get_ptr_LaunchEnableForConcurrentThreadsAt_Server__App = new LaunchEnableForConcurrentThreadsAt_Server__App();
	while (stat_CLASS_get_ptr_LaunchEnableForConcurrentThreadsAt_Server__App() == nullptr) { }
}
void CLIBLaunchQueAtServer::LaunchEnableForConcurrentThreadsAt_Server__Framework::stat_CLASS_boot3_INITIALISE_LaunchEnableForConcurrentThreadsAt_Server__Framework() {
	stat_CLASS_boot3_INITIALISE_LaunchEnableForConcurrentThreadsAt_Server__App();
	stat_CLASS_boot3_INITIALISE_LaunchEnableForConcurrentThreadsAt_Server__Global();
}
void CLIBLaunchQueAtServer::LaunchEnableForConcurrentThreadsAt_Server__Framework::stat_CLASS_boot3_INITIALISE_LaunchEnableForConcurrentThreadsAt_Server__Global() {
	_stat_CLASS_ptr_LaunchEnableForConcurrentThreadsAt_Server__Global = new LaunchEnableForConcurrentThreadsAt_Server__Global();
	while (stat_CLASS_get_ptr_LaunchEnableForConcurrentThreadsAt_Server__Global() == nullptr) { }
}
CLIBLaunchQueAtServer::LaunchEnableForConcurrentThreadsAt_Server__App* CLIBLaunchQueAtServer::LaunchEnableForConcurrentThreadsAt_Server__Framework::stat_CLASS_get_ptr_LaunchEnableForConcurrentThreadsAt_Server__App() {
	return _stat_CLASS_get_ptr_LaunchEnableForConcurrentThreadsAt_Server__App;
}
CLIBLaunchQueAtServer::LaunchEnableForConcurrentThreadsAt_Server__Global* CLIBLaunchQueAtServer::LaunchEnableForConcurrentThreadsAt_Server__Framework::stat_CLASS_get_ptr_LaunchEnableForConcurrentThreadsAt_Server__Global() {
	return _stat_CLASS_ptr_LaunchEnableForConcurrentThreadsAt_Server__Global;
}