//
// Created by brentonjames on 6/29/26.
//

#ifndef TESTBENCH_WRITEQUE_SERVERINPUTRECIEVE_H
#define TESTBENCH_WRITEQUE_SERVERINPUTRECIEVE_H


class WriteQue_ServerInputRecieve {
};


#endif //TESTBENCH_WRITEQUE_SERVERINPUTRECIEVE_H
