#include "../include/WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework.h"
	CLIBWriteQueAt_Server_LaunchQueConditionCode::WriteEnableForThreadsAt_Server_LaunchQueConditionCode_App* CLIBWriteQueAt_Server_LaunchQueConditionCode::WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework_App;
	CLIBWriteQueAt_Server_LaunchQueConditionCode::WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Global* CLIBWriteQueAt_Server_LaunchQueConditionCode::WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework_Global;
// public.
	CLIBWriteQueAt_Server_LaunchQueConditionCode::WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework::WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework() {

	}
	CLIBWriteQueAt_Server_LaunchQueConditionCode::WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework::~WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework() {
		delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework_App;
		delete _stat_CLASS_ptr_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework_Global;
	}
	void CLIBWriteQueAt_Server_LaunchQueConditionCode::WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework::dyn_CLASS_create_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Architecture() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework();
	}
	void CLIBWriteQueAt_Server_LaunchQueConditionCode::WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework::dyn_CLASS_create_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Global_and_Settings()
	{
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Global();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Global();
	}
	CLIBWriteQueAt_Server_LaunchQueConditionCode::WriteEnableForThreadsAt_Server_LaunchQueConditionCode_App* CLIBWriteQueAt_Server_LaunchQueConditionCode::WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_App() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_App();
	}
	CLIBWriteQueAt_Server_LaunchQueConditionCode::WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Global* CLIBWriteQueAt_Server_LaunchQueConditionCode::WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Global() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Global();
	}
	void CLIBWriteQueAt_Server_LaunchQueConditionCode::WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_App();
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Global();
	}
	void CLIBWriteQueAt_Server_LaunchQueConditionCode::WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework() {
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_App();
	}
	void CLIBWriteQueAt_Server_LaunchQueConditionCode::WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Global() {
		pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Global();
	}
// private.
	void CLIBWriteQueAt_Server_LaunchQueConditionCode::WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework_App = nullptr;
	}
	void CLIBWriteQueAt_Server_LaunchQueConditionCode::WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework_Global = nullptr;
	}
	void CLIBWriteQueAt_Server_LaunchQueConditionCode::WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework_App = new class CLIBWriteQueAt_Server_LaunchQueConditionCode::WriteEnableForThreadsAt_Server_LaunchQueConditionCode_App();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_App() == nullptr) {}
	}
	void CLIBWriteQueAt_Server_LaunchQueConditionCode::WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework::pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework_Global = new class CLIBWriteQueAt_Server_LaunchQueConditionCode::WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Global();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Global() == nullptr) {}
	}
	CLIBWriteQueAt_Server_LaunchQueConditionCode::WriteEnableForThreadsAt_Server_LaunchQueConditionCode_App* CLIBWriteQueAt_Server_LaunchQueConditionCode::WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_App()
	{
		return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework_App;
	}
	CLIBWriteQueAt_Server_LaunchQueConditionCode::WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Global* CLIBWriteQueAt_Server_LaunchQueConditionCode::WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_Server_LaunchQueConditionCode_Framework_Global;
	}