#include "../include/WriteEnableForThreadsAt_ServerInputReceive_Framework.h"
CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive_App* CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive_Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive_Framework_App;
	CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive_Global* CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive_Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_ServerInputReceive_Framework_Global;
// public.
	CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive_Framework::WriteEnableForThreadsAt_ServerInputReceive_Framework() {

	}
	CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive_Framework::~WriteEnableForThreadsAt_ServerInputReceive_Framework() {
		delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive_Framework_App;
		delete _stat_CLASS_ptr_WriteEnableForThreadsAt_ServerInputReceive_Framework_Global;
	}
	void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive_Framework::dyn_CLASS_create_WriteEnableForThreadsAt_ServerInputReceive_Architecture() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerInputReceive_Framework();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerInputReceive_Framework();
	}
	void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive_Framework::dyn_CLASS_create_WriteEnableForThreadsAt_ServerInputReceive_Global_and_Settings()
	{
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerInputReceive_Global();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerInputReceive_Global();
	}
	CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive_App* CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive_Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive_App() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive_App();
	}
	CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive_Global* CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive_Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive_Global() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive_Global();
	}
	void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive_Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerInputReceive_Framework() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerInputReceive_App();
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerInputReceive_Global();
	}
	void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive_Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerInputReceive_Framework() {
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerInputReceive_App();
	}
	void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive_Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerInputReceive_Global() {
		pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerInputReceive_Global();
	}
// private.
	void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive_Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerInputReceive_App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive_Framework_App = nullptr;
	}
	void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive_Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerInputReceive_Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_ServerInputReceive_Framework_Global = nullptr;
	}
	void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive_Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerInputReceive_App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive_Framework_App = new class CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive_App();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive_App() == nullptr) {}
	}
	void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive_Framework::pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerInputReceive_Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_ServerInputReceive_Framework_Global = new class CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive_Global();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive_Global() == nullptr) {}
	}
	CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive_App* CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive_Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive_App()
	{
		return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive_Framework_App;
	}
	CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive_Global* CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive_Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive_Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_ServerInputReceive_Framework_Global;
	}