#include "WriteEnableForThreadsAt_ServerInputReceive__Framework.h"
CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__App* CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__Framework__App;
	CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Global* CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_ServerInputReceive__Framework__Global;
// public.
	CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::WriteEnableForThreadsAt_ServerInputReceive__Framework() {

	}
	CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::~WriteEnableForThreadsAt_ServerInputReceive__Framework() {
		delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__Framework__App;
		delete _stat_CLASS_ptr_WriteEnableForThreadsAt_ServerInputReceive__Framework__Global;
	}
	void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::dyn_CLASS_create_WriteEnableForThreadsAt_ServerInputReceive__Architecture() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerInputReceive__Framework();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerInputReceive__Framework();
	}
	void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::dyn_CLASS_create_WriteEnableForThreadsAt_ServerInputReceive__Global_and_Settings()
	{
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerInputReceive__Global();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerInputReceive__Global();
	}
	CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__App* CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__App() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__App();
	}
	CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Global* CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__Global() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__Global();
	}
	void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerInputReceive__Framework() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerInputReceive__App();
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerInputReceive__Global();
	}
	void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerInputReceive__Framework() {
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerInputReceive__App();
	}
	void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerInputReceive__Global() {
		pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerInputReceive__Global();
	}
// private.
	void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerInputReceive__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__Framework__App = nullptr;
	}
	void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerInputReceive__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_ServerInputReceive__Framework__Global = nullptr;
	}
	void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerInputReceive__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__Framework__App = new class CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__App();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__App() == nullptr) {}
	}
	void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerInputReceive__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_ServerInputReceive__Framework__Global = new class CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Global();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__Global() == nullptr) {}
	}
	CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__App* CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__App()
	{
		return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__Framework__App;
	}
	CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Global* CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_ServerInputReceive__Framework__Global;
	}