#include "WriteEnableForThreadsAt_ServerConditionCode__Framework.h"
CLIBWriteQueAtServerConditionCode::WriteEnableForThreadsAt_ServerConditionCode__App* CLIBWriteQueAtServerConditionCode::WriteEnableForThreadsAt_ServerConditionCode__Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerConditionCode__Framework__App;
	CLIBWriteQueAtServerConditionCode::WriteEnableForThreadsAt_ServerConditionCode__Global* CLIBWriteQueAtServerConditionCode::WriteEnableForThreadsAt_ServerConditionCode__Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_ServerConditionCode__Framework__Global;
// public.
	CLIBWriteQueAtServerConditionCode::WriteEnableForThreadsAt_ServerConditionCode__Framework::WriteEnableForThreadsAt_ServerConditionCode__Framework() {

	}
	CLIBWriteQueAtServerConditionCode::WriteEnableForThreadsAt_ServerConditionCode__Framework::~WriteEnableForThreadsAt_ServerConditionCode__Framework() {
		delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerConditionCode__Framework__App;
		delete _stat_CLASS_ptr_WriteEnableForThreadsAt_ServerConditionCode__Framework__Global;
	}
	void CLIBWriteQueAtServerConditionCode::WriteEnableForThreadsAt_ServerConditionCode__Framework::dyn_CLASS_create_WriteEnableForThreadsAt_ServerConditionCode__Architecture() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerConditionCode__Framework();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerConditionCode__Framework();
	}
	void CLIBWriteQueAtServerConditionCode::WriteEnableForThreadsAt_ServerConditionCode__Framework::dyn_CLASS_create_WriteEnableForThreadsAt_ServerConditionCode__Global_and_Settings()
	{
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerConditionCode__Global();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerConditionCode__Global();
	}
	CLIBWriteQueAtServerConditionCode::WriteEnableForThreadsAt_ServerConditionCode__App* CLIBWriteQueAtServerConditionCode::WriteEnableForThreadsAt_ServerConditionCode__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerConditionCode__App() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerConditionCode__App();
	}
	CLIBWriteQueAtServerConditionCode::WriteEnableForThreadsAt_ServerConditionCode__Global* CLIBWriteQueAtServerConditionCode::WriteEnableForThreadsAt_ServerConditionCode__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerConditionCode__Global() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerConditionCode__Global();
	}
	void CLIBWriteQueAtServerConditionCode::WriteEnableForThreadsAt_ServerConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerConditionCode__Framework() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerConditionCode__App();
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerConditionCode__Global();
	}
	void CLIBWriteQueAtServerConditionCode::WriteEnableForThreadsAt_ServerConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerConditionCode__Framework() {
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerConditionCode__App();
	}
	void CLIBWriteQueAtServerConditionCode::WriteEnableForThreadsAt_ServerConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerConditionCode__Global() {
		pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerConditionCode__Global();
	}
// private.
	void CLIBWriteQueAtServerConditionCode::WriteEnableForThreadsAt_ServerConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerConditionCode__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerConditionCode__Framework__App = nullptr;
	}
	void CLIBWriteQueAtServerConditionCode::WriteEnableForThreadsAt_ServerConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerConditionCode__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_ServerConditionCode__Framework__Global = nullptr;
	}
	void CLIBWriteQueAtServerConditionCode::WriteEnableForThreadsAt_ServerConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerConditionCode__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerConditionCode__Framework__App = new class CLIBWriteQueAtServerConditionCode::WriteEnableForThreadsAt_ServerConditionCode__App();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerConditionCode__App() == nullptr) {}
	}
	void CLIBWriteQueAtServerConditionCode::WriteEnableForThreadsAt_ServerConditionCode__Framework::pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerConditionCode__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_ServerConditionCode__Framework__Global = new class CLIBWriteQueAtServerConditionCode::WriteEnableForThreadsAt_ServerConditionCode__Global();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerConditionCode__Global() == nullptr) {}
	}
	CLIBWriteQueAtServerConditionCode::WriteEnableForThreadsAt_ServerConditionCode__App* CLIBWriteQueAtServerConditionCode::WriteEnableForThreadsAt_ServerConditionCode__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerConditionCode__App()
	{
		return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerConditionCode__Framework__App;
	}
	CLIBWriteQueAtServerConditionCode::WriteEnableForThreadsAt_ServerConditionCode__Global* CLIBWriteQueAtServerConditionCode::WriteEnableForThreadsAt_ServerConditionCode__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerConditionCode__Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_ServerConditionCode__Framework__Global;
	}