#include "WriteEnableForThreadsAt_SIMULATION__Framework.h"
#include "../include/WriteEnableForThreadsAt_SIMULATION__App.h"
#include "../include/WriteEnableForThreadsAt_SIMULATION__Control.h"
#include "../include/WriteEnableForThreadsAt_SIMULATION__Global.h"
#include <iostream>
CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION__App* CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION__Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION__App;
CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION__Global* CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION__Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_SIMULATION__Global;
// public.
CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION__Framework::WriteEnableForThreadsAt_SIMULATION__Framework()
{
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SIMULATION__Framework();
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SIMULATION__Framework();
}
CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION__Framework::~WriteEnableForThreadsAt_SIMULATION__Framework()
{
	delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION__App;
	delete _stat_CLASS_ptr_WriteEnableForThreadsAt_SIMULATION__Global;
}
CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION__App* CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION__App() {
	return stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION__App();
}
CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION__Global* CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION__Global() {
	return stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION__Global();
}
void CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION__Framework::dyn_REG_boot1_DEFINE_WriteEnableForThreadsAt_SIMULATION__Framework(WriteEnableForThreadsAt_SIMULATION__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION__App__Control()->dyn_REG_boot1_DEFINE_WriteEnableForThreadsAt_SIMULATION__Control(obj);
}
void CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION__Framework::dyn_REG_boot2_SUBSTANTIATE_WriteEnableForThreadsAt_SIMULATION__Framework(WriteEnableForThreadsAt_SIMULATION__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION__App__Control()->dyn_REG_boot2_SUBSTANTIATE_WriteEnableForThreadsAt_SIMULATION__Control(obj);
}
void CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION__Framework::dyn_REG_boot3_INITIALISE_WriteEnableForThreadsAt_SIMULATION__Framework(WriteEnableForThreadsAt_SIMULATION__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION__App__Control()->dyn_REG_boot3_INITIALISE_WriteEnableForThreadsAt_SIMULATION__Control(obj);
}
void CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION__Framework::dyn_boot4_PGM_INSTANTIATION_WriteEnableForThreadsAt_SIMULATION__Framework(WriteEnableForThreadsAt_SIMULATION__Framework* obj) {

}
void CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SIMULATION__Framework() {
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SIMULATION__App();
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SIMULATION__Global();
}
void CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SIMULATION__Framework() {
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SIMULATION__App();
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SIMULATION__Global();
}
// private.
void CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SIMULATION__App()
{
	_stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION__App = nullptr;
}
void CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_SIMULATION__Global()
{
	_stat_CLASS_ptr_WriteEnableForThreadsAt_SIMULATION__Global = NULL;
}
void CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SIMULATION__App()
{
	_stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION__App = new class CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION__App();
	while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION__App() == nullptr) {}
}
void CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_SIMULATION__Global()
{
	_stat_CLASS_ptr_WriteEnableForThreadsAt_SIMULATION__Global = new class CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION__Global();
	while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION__Global() == NULL) {}
}
CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION__App* CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION__App()
{
	return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION__App;
}
CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION__Global* CLIBWriteQueAtSIMULATION::WriteEnableForThreadsAt_SIMULATION__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_SIMULATION__Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_SIMULATION__Global;
	}