#include "../include/WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App.h"
#include "../include/WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control.h"
#include "../include/WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework.h"
#include "../include/WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control.h"
#include <cstdint>
#include <iostream>
#include <ostream>
    CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control* CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App::_stat_CLASS_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control;
    CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App(uint8_t threadId) {
        CLIB_ThreadLogs::CLIB_ThreadLogs::stat_APP_FUNCT_CLIB_ThreadLogs_printConsoleAndLog(threadId, new std::string(" :: entered LIB :: CLIBWriteQueAtOpenEpiCentre_ConditionCode : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)."));
        CLASS_boot0_DECLARE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId);
        CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId);
        CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId);
        CLIB_ThreadLogs::CLIB_ThreadLogs::stat_APP_FUNCT_CLIB_ThreadLogs_printConsoleAndLog(threadId, new std::string(" :: entered LIB :: CLIBWriteQueAtOpenEpiCentre_ConditionCode : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)."));
    }
    CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App::~WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App() {
        std::cout << "thread "  << 0 << " :: entered LIB :: CLIBWriteQueAtOpenEpiCentre_ConditionCode : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)."));
        delete _stat_CLASS_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control;
        std::cout << "thread "  << 0 << " :: entered LIB :: CLIBWriteQueAtOpenEpiCentre_ConditionCode : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)."));
    }
    void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App::CLASS_boot0_DECLARE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(uint8_t threadId) {
        CLIB_ThreadLogs::CLIB_ThreadLogs::stat_APP_FUNCT_CLIB_ThreadLogs_printConsoleAndLog(threadId, new std::string(" :: entered LIB :: CLIBWriteQueAtOpenEpiCentre_ConditionCode : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control : CLASS_boot0_DECLARE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)."));
        CLIB_ThreadLogs::CLIB_ThreadLogs::stat_APP_FUNCT_CLIB_ThreadLogs_printConsoleAndLog(threadId, new std::string(" :: entered LIB :: CLIBWriteQueAtOpenEpiCentre_ConditionCode : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control : CLASS_boot0_DECLARE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)."));
    }
    void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App::CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(uint8_t threadId) {
        CLIB_ThreadLogs::CLIB_ThreadLogs::stat_APP_FUNCT_CLIB_ThreadLogs_printConsoleAndLog(threadId, new std::string(" :: entered LIB :: CLIBWriteQueAtOpenEpiCentre_ConditionCode : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control : CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)."));
        stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId);
        CLIB_ThreadLogs::CLIB_ThreadLogs::stat_APP_FUNCT_CLIB_ThreadLogs_printConsoleAndLog(threadId, new std::string(" :: entered LIB :: CLIBWriteQueAtOpenEpiCentre_ConditionCode : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control : CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)."));
    }
    void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App::CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(uint8_t threadId) {
        CLIB_ThreadLogs::CLIB_ThreadLogs::stat_APP_FUNCT_CLIB_ThreadLogs_printConsoleAndLog(threadId, new std::string(" :: entered LIB :: CLIBWriteQueAtOpenEpiCentre_ConditionCode : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control : CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)."));
        stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId);
        CLIB_ThreadLogs::CLIB_ThreadLogs::stat_APP_FUNCT_CLIB_ThreadLogs_printConsoleAndLog(threadId, new std::string(" :: entered LIB :: CLIBWriteQueAtOpenEpiCentre_ConditionCode : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control : CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)."));
    }
    void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App::REG_boot0_DECLARE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(uint8_t threadId) {
        CLIB_ThreadLogs::CLIB_ThreadLogs::stat_APP_FUNCT_CLIB_ThreadLogs_printConsoleAndLog(threadId, new std::string(" :: entered LIB :: CLIBWriteQueAtOpenEpiCentre_ConditionCode : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control : REG_boot0_DECLARE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)."));
        CLIB_ThreadLogs::CLIB_ThreadLogs::stat_APP_FUNCT_CLIB_ThreadLogs_printConsoleAndLog(threadId, new std::string(" :: entered LIB :: CLIBWriteQueAtOpenEpiCentre_ConditionCode : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control : REG_boot0_DECLARE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)."));
    }
    void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App::REG_boot1_DEFINE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(uint8_t threadId, WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework* obj) {
        CLIB_ThreadLogs::CLIB_ThreadLogs::stat_APP_FUNCT_CLIB_ThreadLogs_printConsoleAndLog(threadId, new std::string(" :: entered LIB :: CLIBWriteQueAtOpenEpiCentre_ConditionCode : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control : REG_boot1_DEFINE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)."));
        CLIB_ThreadLogs::CLIB_ThreadLogs::stat_APP_FUNCT_CLIB_ThreadLogs_printConsoleAndLog(threadId, new std::string(" :: entered LIB :: CLIBWriteQueAtOpenEpiCentre_ConditionCode : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control : REG_boot1_DEFINE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)."));
    }
    void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App::REG_boot2_SUBSTANTIATE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(uint8_t threadId, WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework* obj) {
        CLIB_ThreadLogs::CLIB_ThreadLogs::stat_APP_FUNCT_CLIB_ThreadLogs_printConsoleAndLog(threadId, new std::string(" :: entered LIB :: CLIBWriteQueAtOpenEpiCentre_ConditionCode : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control : REG_boot2_SUBSTANTIATE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)."));
        CLIB_ThreadLogs::CLIB_ThreadLogs::stat_APP_FUNCT_CLIB_ThreadLogs_printConsoleAndLog(threadId, new std::string(" :: entered LIB :: CLIBWriteQueAtOpenEpiCentre_ConditionCode : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control : REG_boot2_SUBSTANTIATE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)."));
    }
    void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App::REG_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(uint8_t threadId, WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework* obj) {
        CLIB_ThreadLogs::CLIB_ThreadLogs::stat_APP_FUNCT_CLIB_ThreadLogs_printConsoleAndLog(threadId, new std::string(" :: entered LIB :: CLIBWriteQueAtOpenEpiCentre_ConditionCode : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control : REG_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)."));
        CLIB_ThreadLogs::CLIB_ThreadLogs::stat_APP_FUNCT_CLIB_ThreadLogs_printConsoleAndLog(threadId, new std::string(" :: entered LIB :: CLIBWriteQueAtOpenEpiCentre_ConditionCode : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control : REG_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)."));
    }
    void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App::dyn_APP_FUNCT_write_End(uint8_t threadId, WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework* obj, uint8_t coreId) {
        CLIB_ThreadLogs::CLIB_ThreadLogs::stat_APP_FUNCT_CLIB_ThreadLogs_printConsoleAndLog(threadId, new std::string(" :: entered LIB :: CLIBWriteQueAtOpenEpiCentre_ConditionCode : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control : dyn_APP_FUNCT_write_End(threadId)."));
        while (obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)->dyn_REG_get_FLAG_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control_isWriteEndThreadRELASE_ONE(threadId)) {
            obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)->dyn_APP_FUNCT_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control_dynamicIn(obj, coreId);
            obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)->dyn_REG_set_FLAG_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control_isWriteEndThreadRELASE_ONE(false);
        }
        obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)->dyn_REG_set_FLAG_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control_isWriteEndThreadRELASE_ONE(true);
        obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)->dyn_REG_set_FLAG_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control_writeCycle_Try_WriteEndthreadId_Index(obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)->dyn_REG_get_FLAG_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control_writeCycle_Try_WriteEndthreadId_Index(threadId)+1);
        if (obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)->dyn_REG_get_FLAG_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control_writeCycle_Try_WriteEndthreadId_Index(threadId) == obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control(threadId)->dyn_REG_get_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_number_Of_Implemented_Threads(threadId)) {
            obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)->dyn_REG_set_FLAG_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control_writeCycle_Try_WriteEndthreadId_Index(0);
        }
        obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)->dyn_REG_set_Item_On_list_Of_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control_2ibt_FLAG_WriteState(coreId, obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control(threadId)->dyn_REG_get_ptr_CONST_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_2bitFLAG_IDLE());
        obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)->dyn_APP_FUNCT_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control_writeQue_Update(obj);
        obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)->dyn_APP_FUNCT_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control_writeEnable_SortQue(obj);
        obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)->dyn_REG_set_FLAG_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control_isWriteEndThreadRELASE_REMAINING(true);
        obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)->dyn_REG_set_FLAG_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control_isWriteStartThreadRELASE_REMAINING(true);
        CLIB_ThreadLogs::CLIB_ThreadLogs::stat_APP_FUNCT_CLIB_ThreadLogs_printConsoleAndLog(threadId, new std::string(" :: entered LIB :: CLIBWriteQueAtOpenEpiCentre_ConditionCode : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control : dyn_APP_FUNCT_write_End(threadId)."));
    }
    void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App::dyn_APP_FUNCT_write_Start(uint8_t threadId, WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework* obj, uint8_t coreId)
    {
        CLIB_ThreadLogs::CLIB_ThreadLogs::stat_APP_FUNCT_CLIB_ThreadLogs_printConsoleAndLog(threadId, new std::string(" :: entered LIB :: CLIBWriteQueAtOpenEpiCentre_ConditionCode : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control : dyn_APP_FUNCT_write_Start(threadId)."));
        while (obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)->dyn_REG_get_FLAG_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control_isWriteStartThreadRELASE_ONE(threadId)) {
            obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)->dyn_APP_FUNCT_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control_dynamicIn(obj, coreId);
            obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)->dyn_REG_set_FLAG_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control_isWriteStartThreadRELASE_ONE(false);
        }
        obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)->dyn_REG_set_FLAG_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control_isWriteStartThreadRELASE_ONE(true);
        obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)->dyn_REG_set_FLAG_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control_writeCycle_Try_WriteStartthreadId_Index(obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)->dyn_REG_get_FLAG_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control_writeCycle_Try_WriteStartthreadId_Index(threadId)+1);
        if (obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)->dyn_REG_get_FLAG_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control_writeCycle_Try_WriteStartthreadId_Index(threadId) == obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control(threadId)->dyn_REG_get_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_number_Of_Implemented_Threads(threadId)) {
            obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)->dyn_REG_set_FLAG_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control_writeCycle_Try_WriteStartthreadId_Index(0);
        }
        obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)->dyn_APP_FUNCT_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control_writeQue_Update(obj);
        obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)->dyn_APP_FUNCT_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control_writeEnable_SortQue(obj);
        obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App(threadId)->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)->dyn_APP_FUNCT_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control_writeEnable_Activate(obj, coreId);
        CLIB_ThreadLogs::CLIB_ThreadLogs::stat_APP_FUNCT_CLIB_ThreadLogs_printConsoleAndLog(threadId, new std::string(" :: entered LIB :: CLIBWriteQueAtOpenEpiCentre_ConditionCode : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control : dyn_APP_FUNCT_write_Start(threadId)."));
    }
    CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control* CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(uint8_t threadId) {
        CLIB_ThreadLogs::CLIB_ThreadLogs::stat_APP_FUNCT_CLIB_ThreadLogs_printConsoleAndLog(threadId, new std::string(" :: <= class : dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)."));
        return stat_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId);
    }
    void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(uint8_t threadId) {
        CLIB_ThreadLogs::CLIB_ThreadLogs::stat_APP_FUNCT_CLIB_ThreadLogs_printConsoleAndLog(threadId, new std::string(" :: entered LIB :: CLIBWriteQueAtOpenEpiCentre_ConditionCode : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control : stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)."));
        _stat_CLASS_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control = nullptr;
        CLIB_ThreadLogs::CLIB_ThreadLogs::stat_APP_FUNCT_CLIB_ThreadLogs_printConsoleAndLog(threadId, new std::string(" :: entered LIB :: CLIBWriteQueAtOpenEpiCentre_ConditionCode : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control : stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)."));
    }
    void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(uint8_t threadId) {
        CLIB_ThreadLogs::CLIB_ThreadLogs::stat_APP_FUNCT_CLIB_ThreadLogs_printConsoleAndLog(threadId, new std::string(" :: entered LIB :: CLIBWriteQueAtOpenEpiCentre_ConditionCode : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control : stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)."));
        _stat_CLASS_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control = new class CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control(threadId);
        while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId) == nullptr) {}
        CLIB_ThreadLogs::CLIB_ThreadLogs::stat_APP_FUNCT_CLIB_ThreadLogs_printConsoleAndLog(threadId, new std::string(" :: entered LIB :: CLIBWriteQueAtOpenEpiCentre_ConditionCode : WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control : stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)."));
    }
    CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App_Control* CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App::stat_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(uint8_t threadId) {
        CLIB_ThreadLogs::CLIB_ThreadLogs::stat_APP_FUNCT_CLIB_ThreadLogs_printConsoleAndLog(threadId, new std::string(" :: <= class : stat_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control(threadId)."));
        return _stat_CLASS_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App_Control;
    }