#include "../include/WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework.h"
CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__App* CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework__App;
	CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Global* CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework__Global;
// public.
	CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework() {

	}
	CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework::~WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework() {
		delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework__App;
		delete _stat_CLASS_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework__Global;
	}
	void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework::dyn_CLASS_create_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Architecture() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework();
	}
	void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework::dyn_CLASS_create_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Global_and_Settings()
	{
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Global();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Global();
	}
	CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__App* CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__App() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__App();
	}
	CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Global* CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Global() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Global();
	}
	void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__App();
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Global();
	}
	void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework() {
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__App();
	}
	void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Global() {
		pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Global();
	}
// private.
	void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework__App = nullptr;
	}
	void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework__Global = nullptr;
	}
	void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework__App = new class CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__App();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__App() == nullptr) {}
	}
	void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework::pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework__Global = new class CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Global();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Global() == nullptr) {}
	}
	CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__App* CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__App()
	{
		return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework__App;
	}
	CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Global* CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode__Framework__Global;
	}