#include "../include/WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework.h"
CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App* CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App;
	CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Global* CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_Global;
// public.
	CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework() {

	}
	CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework::~WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework() {
		delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App;
		delete _stat_CLASS_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_Global;
	}
	void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework::dyn_CLASS_create_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Architecture() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework();
	}
	void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework::dyn_CLASS_create_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Global_and_Settings()
	{
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Global();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Global();
	}
	CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App* CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App();
	}
	CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Global* CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Global() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Global();
	}
	void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App();
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Global();
	}
	void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework() {
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App();
	}
	void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Global() {
		pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Global();
	}
// private.
	void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App = nullptr;
	}
	void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_Global = nullptr;
	}
	void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App = new class CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App() == nullptr) {}
	}
	void CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework::pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_Global = new class CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Global();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Global() == nullptr) {}
	}
	CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App* CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_App()
	{
		return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_App;
	}
	CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Global* CLIBWriteQueAtOpenEpiCentre_ConditionCode::WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_OpenEpiCentre_ConditionCode_Framework_Global;
	}