#include "../include/WriteEnableForThreadsAt_ServerInputReceive__Framework.h"
#include "../include/WriteEnableForThreadsAt_ServerInputReceive__App.h"
#include "../include/WriteEnableForThreadsAt_ServerInputReceive__Control.h"
#include "../include/WriteEnableForThreadsAt_ServerInputReceive__Global.h"
#include <iostream>
CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__App* CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__App;
CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Global* CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_ServerInputReceive__Global;
// public.
CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::WriteEnableForThreadsAt_ServerInputReceive__Framework()
{
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerInputReceive__Framework();
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerInputReceive__Framework();
}
CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::~WriteEnableForThreadsAt_ServerInputReceive__Framework()
{
	delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__App;
	delete _stat_CLASS_ptr_WriteEnableForThreadsAt_ServerInputReceive__Global;
}
CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__App* CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__App() {
	return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__App();
}
CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Global* CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__Global() {
	return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__Global();
}
void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::dyn_REG_boot1_DEFINE_WriteEnableForThreadsAt_ServerInputReceive__Framework(WriteEnableForThreadsAt_ServerInputReceive__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__App__Control()->dyn_REG_boot1_DEFINE_WriteEnableForThreadsAt_ServerInputReceive__Control(obj);
}
void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::dyn_REG_boot2_SUBSTANTIATE_WriteEnableForThreadsAt_ServerInputReceive__Framework(WriteEnableForThreadsAt_ServerInputReceive__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__App__Control()->dyn_REG_boot2_SUBSTANTIATE_WriteEnableForThreadsAt_ServerInputReceive__Control(obj);
}
void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::dyn_REG_boot3_INITIALISE_WriteEnableForThreadsAt_ServerInputReceive__Framework(WriteEnableForThreadsAt_ServerInputReceive__Framework* obj) {
	obj->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__App()->dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__App__Control()->dyn_REG_boot3_INITIALISE_WriteEnableForThreadsAt_ServerInputReceive__Control(obj);
}
void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::dyn_boot4_PGM_INSTANTIATION_WriteEnableForThreadsAt_ServerInputReceive__Framework(WriteEnableForThreadsAt_ServerInputReceive__Framework* obj) {

}
void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerInputReceive__Framework() {
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerInputReceive__App();
	stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerInputReceive__Global();
}
void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerInputReceive__Framework() {
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerInputReceive__App();
	stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerInputReceive__Global();
}
// private.
void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerInputReceive__App()
{
	_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__App = nullptr;
}
void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ServerInputReceive__Global()
{
	_stat_CLASS_ptr_WriteEnableForThreadsAt_ServerInputReceive__Global = NULL;
}
void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerInputReceive__App()
{
	_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__App = new class CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__App();
	while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__App() == nullptr) {}
}
void CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ServerInputReceive__Global()
{
	_stat_CLASS_ptr_WriteEnableForThreadsAt_ServerInputReceive__Global = new class CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Global();
	while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__Global() == NULL) {}
}
CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__App* CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__App()
{
	return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__App;
}
CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Global* CLIBWriteQueAtServerInputReceive::WriteEnableForThreadsAt_ServerInputReceive__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ServerInputReceive__Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_ServerInputReceive__Global;
	}